A par of bugfix.

diff --git a/recognize b/recognize
--- a/recognize
+++ b/recognize
@@ -14,6 +14,10 @@
    #  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 # TODO, make this use the mode, context and custom sed script
 
+#
+# Usage: recognize "Text to be recognized"
+#
+
 cd ${0%/*}
 
 USER_DIR=$HOME/.lispeak
@@ -21,8 +25,10 @@ rm $HOME/.lispeak/bin/lispeak.py
 rm $HOME/.lispeak/services/lispeak.py
 
 while read line           
-do          
-	export "$line"        
+do
+  if [ ! "${line:0:1}" = "#" ];then
+	export "$line"
+  fi
 done <$USER_DIR/UserInfo
 
 # Try to run a command in ./Recognition/bin with useful errors.
@@ -123,6 +129,11 @@ if [ $mode = "main" ]; then
         fi
     fi
 
+    if [ ! -e "./Recognition/modes/main.dic" ];then
+       echo "Installation error: main.dic not found"
+       exit 5
+    fi
+    
     COMMAND=$(./Recognition/dictionary "$speech" "./Recognition/modes/main.dic")
 
     echo $speech
@@ -130,7 +141,9 @@ if [ $mode = "main" ]; then
     EXIT=$?
 
     if [ "$EXIT" == 0 ];then
-        run_command "$COMMAND"
+        if [ ! -z "$COMMAND" ];then
+            run_command "$COMMAND"
+        fi
         exit 0
     elif [ "$EXIT" == 2 ];then
         ./Recognition/bin/result Error "'$speech'" "is not a recognized command" ""
